### ISSUE TITLE
accidental internal seq allocation

### ISSUE THREAD

**Issue by ghadishayban** [pjstadig/reducible-stream#1]
This line [1] accidentally allocates an internal seq for the streams.  What do you think about making this library into a pure reducibles:

``` clj
(defn supply
  [f eof]
  (reify clojure.lang.IReduceInit
    (reduce [_ rf init]
      (loop [res init]
        (let [v (f)]
          (if (identical? v eof)
            res
            (let [res (rf res v)]
              (if (reduced? res)
                @res
                (recur res)))))))))

;; dual to (line-seq rdr)
(supply #(or (.readLine rdr) ::eof) ::eof)
```

[1] https://github.com/pjstadig/reducible-stream/blob/071d6a88d7153867d2cc3c3f2577406599f34797/src/pjstadig/reducible_stream.clj#L10

**Comment by pjstadig** [comment]
The goal of the library isn't so much to make something that is a pure reducible, as it is to make something that can manage resources when decoding some raw data.

That said, I'm not against the idea of making it a pure reducible, and if you want to work up a PR I'd be glad to merge it.
